POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "change password",
    "emails": ["fabiobatoni@teste.com.br"]
}

###
GET http://localhost:3000/campaigns/curke966m384pl6m2d50

###
PATCH http://localhost:3000/campaigns/cancel/curke966m384pl6m2d50
