POST http://localhost:3000/campaigns

{
    "name": "change",
    "content": "change password",
    "emails": ["fabiobatoni@teste.com.br", "fabio@teste.com"]
}

###
GET http://localhost:3000/campaigns/cuu7a9u6m383cj56tl1g

###
PATCH http://localhost:3000/campaigns/cancel/curke966m384pl6m2d50

###
DELETE http://localhost:3000/campaigns/delete/cusaui66m381qt7ene20
